### ISSUE TITLE
SQL Support

### ISSUE THREAD

**Issue by jordiup** [getdbx/dbx#1]
- [x] add sql connection
- [x] database/table hierachy list view (support multiple dbs under the one connection)
- [x] table editor - render data
- [x] table editor - sorting
- [x] table editor - filtering
- [x] table editor - row delete
- [x] query editor - submit query
- [x] query editor - sql syntax highlight
- [x] query editor - intellisense
- [x] query editor - chatbot
   (for now this is quite a basic implementation of entity/schema defs)
- [x] schema visualiser
- [x] testing
- [x] release

**Comment by jordiup** [comment]
Now live in v0.0.30 🚀
